// Generated by CoffeeScript 1.12.7
(function() {
  var Bluebird, Redis;

  Redis = require('redis');

  Bluebird = require('bluebird');

  Bluebird.promisifyAll(Redis.RedisClient.prototype);

  Bluebird.promisifyAll(Redis.Multi.prototype);

  module.exports = Redis;

}).call(this);
